name: Windows build

on: push

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run with clang-cl for x64
        shell: cmd
        working-directory: .\src
        run: |
          bazelisk run main --platforms=//:windows-x86_64

      - name: Run with clang-cl for x86
        shell: cmd
        working-directory: .\src
        run: |
          bazelisk run main --platforms=//:windows-x86_32

      - name: Build with clang-cl for arm64
        shell: cmd
        working-directory: .\src
        run: |
          bazelisk build main --platforms=//:windows-arm64

  build_arm64:
    runs-on: windows-11-arm
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run with clang-cl for arm64
        shell: cmd
        working-directory: .\src
        run: |
          bazelisk run main --platforms=//:windows-arm64
